from student import *
	
hand = [1,0,0,0,2,1,1,3,1,1,1,0,2,3,2,1,1]

print "hand: " + str(hand)
print "firstFeatureFunction: " + str( firstFeatureFunction(hand) )
print "numberOfCards: " + str(numberOfCards(hand) )
print "numberOfEachHighCard: " + str(numberOfEachHighCard(hand) )
print "numberOfHighCards: " + str(numberOfHighCards(hand) )
print "getNumberOfLosers: " + str(getNumberOfLosers(hand) )
print "getNumberOfMiddles: " + str(getNumberOfMiddles(hand) )
print "getNumberOfWinners: " + str(getNumberOfWinners(hand) )
print "getNumberOfAces: " + str(getNumberOfAces(hand) )
print "hasPair: " + str(hasPair(hand) )
print "hasTriple: " + str(hasTriple(hand) )
print "hasConsecutivePairs: " + str(hasConsecutivePairs(hand) )
print "lengthOfLargestConsecPair: " + str(lengthOfLargestConsecPair(hand) )
print "hasFullHouse: " + str(hasFullHouse(hand) )
print "hasStraight: " + str(hasStraight(hand) )
print "lengthOfBiggestStraight: " + str(lengthOfBiggestStraight(hand) )
print "numberOfCardsLessThanFour: " + str(numberOfCardsLessThanFour(hand) )
print "acesMinusFours: " + str(acesMinusFours(hand) )
print "internetArticle: " + str(internetArticle(hand) )
print "hasPhoenix: " + str(hasPhoenix(hand) )
print "hasDragon: " + str(hasDragon(hand) )
print "hasMa: " + str(hasMa(hand) )
print "hasDog: " + str(hasDog(hand) )
print "averageValueOfHand: " + str(averageValueOfHand(hand) )
print "averageOfLMD: " + str(averageOfLMD(hand) )
print "hasPhoenixAndDragon: " + str(hasPhoenixAndDragon(hand) )
print "getNumberOfSpecialCards: " + str(getNumberOfSpecialCards(hand) )
print "numberOfHighPairs: " + str(numberOfHighPairs(hand) )
print "numberOfHighTriples " + str(numberOfHighTriples(hand) )
print "numberOfSingles " + str(numberOfSingles(hand) )
#print "15: " + str(allCombined(hand) )
